./j4 ../../../../data/all/prop-direct-P2184 ../../../../data/all/prop-direct-P2650 ../../../../data/all/prop-direct-P1366 ../../../../data/all/prop-direct-P1807 ../../../../data/priorities/pri1 0
./j4 ../../../../data/all/prop-direct-P58 ../../../../data/all/prop-direct-P800 ../../../../data/all/prop-direct-P462 ../../../../data/all/prop-direct-P3212 ../../../../data/priorities/pri1 0
./j4 ../../../../data/all/prop-direct-P1026 ../../../../data/all/prop-direct-P1855 ../../../../data/all/prop-direct-P217 ../../../../data/all/prop-direct-P953 ../../../../data/priorities/pri1 0
./j4 ../../../../data/all/prop-direct-P2389 ../../../../data/all/prop-direct-P162 ../../../../data/all/prop-direct-P3761 ../../../../data/all/prop-direct-normalized-P3153 ../../../../data/priorities/pri1 0
./j4 ../../../../data/all/prop-direct-P1454 ../../../../data/all/prop-direct-P740 ../../../../data/all/prop-direct-P1451 ../../../../data/all/prop-direct-P2250 ../../../../data/priorities/pri1 0
./j4 ../../../../data/all/prop-direct-P47 ../../../../data/all/prop-direct-P460 ../../../../data/all/prop-direct-P1875 ../../../../data/all/prop-direct-P836 ../../../../data/priorities/pri1 0
./j4 ../../../../data/all/prop-direct-P3716 ../../../../data/all/prop-direct-P179 ../../../../data/all/prop-direct-P4835 ../../../../data/all/prop-direct-P1267 ../../../../data/priorities/pri1 0
./j4 ../../../../data/all/prop-direct-P2868 ../../../../data/all/prop-direct-P301 ../../../../data/all/prop-direct-P1542 ../../../../data/all/prop-direct-P1344 ../../../../data/priorities/pri1 0
./j4 ../../../../data/all/prop-direct-P277 ../../../../data/all/prop-direct-P1889 ../../../../data/all/prop-direct-P3878 ../../../../data/all/prop-direct-P282 ../../../../data/priorities/pri1 0
./j4 ../../../../data/all/prop-direct-P5053 ../../../../data/all/prop-direct-P1346 ../../../../data/all/prop-direct-P39 ../../../../data/all/prop-direct-normalized-P1006 ../../../../data/priorities/pri1 0
./j4 ../../../../data/all/prop-direct-P1321 ../../../../data/all/prop-direct-P137 ../../../../data/all/prop-direct-normalized-P349 ../../../../data/all/prop-direct-P5198 ../../../../data/priorities/pri1 0
./j4 ../../../../data/all/prop-direct-P750 ../../../../data/all/prop-direct-P1535 ../../../../data/all/prop-direct-P3473 ../../../../data/all/prop-direct-P1324 ../../../../data/priorities/pri1 0
./j4 ../../../../data/all/prop-direct-P437 ../../../../data/all/prop-direct-P710 ../../../../data/all/prop-direct-P553 ../../../../data/all/prop-direct-P112 ../../../../data/priorities/pri1 0
./j4 ../../../../data/all/prop-direct-P3433 ../../../../data/all/prop-direct-P1855 ../../../../data/all/prop-direct-P704 ../../../../data/all/prop-direct-P688 ../../../../data/priorities/pri1 0
./j4 ../../../../data/all/prop-direct-P2293 ../../../../data/all/prop-direct-P684 ../../../../data/all/prop-direct-P353 ../../../../data/all/prop-direct-P227 ../../../../data/priorities/pri1 0
./j4 ../../../../data/all/prop-direct-P3610 ../../../../data/all/prop-direct-P156 ../../../../data/all/prop-direct-P155 ../../../../data/all/prop-direct-P1545 ../../../../data/priorities/pri1 0
./j4 ../../../../data/all/prop-direct-P452 ../../../../data/all/prop-direct-P186 ../../../../data/all/prop-direct-normalized-P4953 ../../../../data/all/prop-direct-P3827 ../../../../data/priorities/pri1 0
./j4 ../../../../data/all/prop-direct-P702 ../../../../data/all/prop-direct-P128 ../../../../data/all/prop-direct-P227 ../../../../data/all/prop-direct-P704 ../../../../data/priorities/pri1 0
./j4 ../../../../data/all/prop-direct-P912 ../../../../data/all/prop-direct-P366 ../../../../data/all/prop-direct-normalized-P2163 ../../../../data/all/prop-direct-normalized-P244 ../../../../data/priorities/pri1 0
./j4 ../../../../data/all/prop-direct-P2515 ../../../../data/all/prop-direct-P40 ../../../../data/all/prop-direct-P1750 ../../../../data/all/prop-direct-P3878 ../../../../data/priorities/pri1 0
./j4 ../../../../data/all/prop-direct-P180 ../../../../data/all/prop-direct-P1535 ../../../../data/all/prop-direct-P4928 ../../../../data/all/prop-direct-P40 ../../../../data/priorities/pri1 0
./j4 ../../../../data/all/prop-direct-P460 ../../../../data/all/prop-direct-P175 ../../../../data/all/prop-direct-P485 ../../../../data/all/prop-direct-P1248 ../../../../data/priorities/pri1 0
./j4 ../../../../data/all/prop-direct-P2416 ../../../../data/all/prop-direct-P1535 ../../../../data/all/prop-direct-P61 ../../../../data/all/prop-direct-P487 ../../../../data/priorities/pri1 0
./j4 ../../../../data/all/prop-direct-P123 ../../../../data/all/prop-direct-P800 ../../../../data/all/prop-direct-P371 ../../../../data/all/prop-direct-P495 ../../../../data/priorities/pri1 0
./j4 ../../../../data/all/prop-direct-P97 ../../../../data/all/prop-direct-P180 ../../../../data/all/prop-direct-P1552 ../../../../data/all/prop-direct-P1889 ../../../../data/priorities/pri1 0
./j4 ../../../../data/all/prop-direct-P157 ../../../../data/all/prop-direct-P180 ../../../../data/all/prop-direct-P2469 ../../../../data/all/prop-direct-P1816 ../../../../data/priorities/pri1 0
./j4 ../../../../data/all/prop-direct-P375 ../../../../data/all/prop-direct-P301 ../../../../data/all/prop-direct-P2067 ../../../../data/all/prop-direct-P176 ../../../../data/priorities/pri1 0
./j4 ../../../../data/all/prop-direct-P516 ../../../../data/all/prop-direct-P1376 ../../../../data/all/prop-direct-P982 ../../../../data/all/prop-direct-P206 ../../../../data/priorities/pri1 0
./j4 ../../../../data/all/prop-direct-P833 ../../../../data/all/prop-direct-P1427 ../../../../data/all/prop-direct-P2186 ../../../../data/all/prop-direct-P197 ../../../../data/priorities/pri1 0
./j4 ../../../../data/all/prop-direct-P1598 ../../../../data/all/prop-direct-P991 ../../../../data/all/prop-direct-P1670 ../../../../data/all/prop-direct-P2949 ../../../../data/priorities/pri1 0
./j4 ../../../../data/all/prop-direct-P1441 ../../../../data/all/prop-direct-P1412 ../../../../data/all/prop-direct-P424 ../../../../data/all/prop-direct-P1014 ../../../../data/priorities/pri1 0
./j4 ../../../../data/all/prop-direct-P541 ../../../../data/all/prop-direct-P301 ../../../../data/all/prop-direct-P902 ../../../../data/all/prop-direct-P1001 ../../../../data/priorities/pri1 0
./j4 ../../../../data/all/prop-direct-P1885 ../../../../data/all/prop-direct-P119 ../../../../data/all/prop-direct-P485 ../../../../data/all/prop-direct-P1004 ../../../../data/priorities/pri1 0
./j4 ../../../../data/all/prop-direct-P552 ../../../../data/all/prop-direct-P1552 ../../../../data/all/prop-direct-P3417 ../../../../data/all/prop-direct-P3219 ../../../../data/priorities/pri1 0
./j4 ../../../../data/all/prop-direct-P1423 ../../../../data/all/prop-direct-P469 ../../../../data/all/prop-direct-P4511 ../../../../data/all/prop-direct-P4614 ../../../../data/priorities/pri1 0
./j4 ../../../../data/all/prop-direct-P908 ../../../../data/all/prop-direct-P155 ../../../../data/all/prop-direct-P1424 ../../../../data/all/prop-direct-P156 ../../../../data/priorities/pri1 0
./j4 ../../../../data/all/prop-direct-P1313 ../../../../data/all/prop-direct-P451 ../../../../data/all/prop-direct-P1447 ../../../../data/all/prop-direct-P39 ../../../../data/priorities/pri1 0
./j4 ../../../../data/all/prop-direct-P177 ../../../../data/all/prop-direct-P1204 ../../../../data/all/prop-direct-P1997 ../../../../data/all/prop-direct-normalized-P269 ../../../../data/priorities/pri1 0
./j4 ../../../../data/all/prop-direct-P1343 ../../../../data/all/prop-direct-P301 ../../../../data/all/prop-direct-P4629 ../../../../data/all/prop-direct-normalized-P227 ../../../../data/priorities/pri1 0
./j4 ../../../../data/all/prop-direct-P5880 ../../../../data/all/prop-direct-P737 ../../../../data/all/prop-direct-P5226 ../../../../data/all/prop-direct-P950 ../../../../data/priorities/pri1 0
./j4 ../../../../data/all/prop-direct-P1465 ../../../../data/all/prop-direct-P461 ../../../../data/all/prop-direct-P1889 ../../../../data/all/prop-direct-P4224 ../../../../data/priorities/pri1 0
./j4 ../../../../data/all/prop-direct-P286 ../../../../data/all/prop-direct-P26 ../../../../data/all/prop-direct-P5476 ../../../../data/all/prop-direct-P166 ../../../../data/priorities/pri1 0
./j4 ../../../../data/all/prop-direct-P196 ../../../../data/all/prop-direct-P2354 ../../../../data/all/prop-direct-P1754 ../../../../data/all/prop-direct-P360 ../../../../data/priorities/pri1 0
./j4 ../../../../data/all/prop-direct-P1652 ../../../../data/all/prop-direct-P1535 ../../../../data/all/prop-direct-P2581 ../../../../data/all/prop-direct-P4254 ../../../../data/priorities/pri1 0
./j4 ../../../../data/all/prop-direct-P488 ../../../../data/all/prop-direct-P127 ../../../../data/all/prop-direct-P2387 ../../../../data/all/prop-direct-P40 ../../../../data/priorities/pri1 0
./j4 ../../../../data/all/prop-direct-P1049 ../../../../data/all/prop-direct-P101 ../../../../data/all/prop-direct-P2115 ../../../../data/all/prop-direct-normalized-P486 ../../../../data/priorities/pri1 0
./j4 ../../../../data/all/prop-direct-P126 ../../../../data/all/prop-direct-P1040 ../../../../data/all/prop-direct-P3835 ../../../../data/all/prop-direct-normalized-P648 ../../../../data/priorities/pri1 0
./j4 ../../../../data/all/prop-direct-P1542 ../../../../data/all/prop-direct-P183 ../../../../data/all/prop-direct-P41 ../../../../data/all/prop-direct-P2390 ../../../../data/priorities/pri1 0
./j4 ../../../../data/all/prop-direct-P3919 ../../../../data/all/prop-direct-P1343 ../../../../data/all/prop-direct-normalized-P648 ../../../../data/all/prop-direct-P675 ../../../../data/priorities/pri1 0
./j4 ../../../../data/all/prop-direct-P1811 ../../../../data/all/prop-direct-P155 ../../../../data/all/prop-direct-P156 ../../../../data/all/prop-direct-P360 ../../../../data/priorities/pri1 0
