./s1 ../../../../data/all/prop-direct-P1151 ../../../../data/all/prop-direct-P155 ../../../../data/all/prop-direct-P1204 ../../../../data/all/prop-direct-P156 1
./s1 ../../../../data/all/prop-direct-P291 ../../../../data/all/prop-direct-P155 ../../../../data/all/prop-direct-P156 ../../../../data/all/prop-direct-P1343 1
./s1 ../../../../data/all/prop-direct-P945 ../../../../data/all/prop-direct-P40 ../../../../data/all/prop-direct-P22 ../../../../data/all/prop-direct-P241 1
./s1 ../../../../data/all/prop-direct-P22 ../../../../data/all/prop-direct-P1875 ../../../../data/all/prop-direct-P138 ../../../../data/all/prop-direct-P3373 1
./s1 ../../../../data/all/prop-direct-P451 ../../../../data/all/prop-direct-P1424 ../../../../data/all/prop-direct-P1423 ../../../../data/all/prop-direct-P1875 1
./s1 ../../../../data/all/prop-direct-P541 ../../../../data/all/prop-direct-P1001 ../../../../data/all/prop-direct-P6 ../../../../data/all/prop-direct-P3602 1
./s1 ../../../../data/all/prop-direct-P177 ../../../../data/all/prop-direct-P974 ../../../../data/all/prop-direct-P403 ../../../../data/all/prop-direct-P2505 1
./s1 ../../../../data/all/prop-direct-P1151 ../../../../data/all/prop-direct-P155 ../../../../data/all/prop-direct-P1204 ../../../../data/all/prop-direct-P156 1
./s1 ../../../../data/all/prop-direct-P4195 ../../../../data/all/prop-direct-P301 ../../../../data/all/prop-direct-P355 ../../../../data/all/prop-direct-P749 1
./s1 ../../../../data/all/prop-direct-P375 ../../../../data/all/prop-direct-P176 ../../../../data/all/prop-direct-P793 ../../../../data/all/prop-direct-P1269 1
./s1 ../../../../data/all/prop-direct-P194 ../../../../data/all/prop-direct-P485 ../../../../data/all/prop-direct-P276 ../../../../data/all/prop-direct-P1001 1
./s1 ../../../../data/all/prop-direct-P2875 ../../../../data/all/prop-direct-P1659 ../../../../data/all/prop-direct-P180 ../../../../data/all/prop-direct-P1687 1
./s1 ../../../../data/all/prop-direct-P559 ../../../../data/all/prop-direct-P155 ../../../../data/all/prop-direct-P642 ../../../../data/all/prop-direct-P2789 1
./s1 ../../../../data/all/prop-direct-P102 ../../../../data/all/prop-direct-P2184 ../../../../data/all/prop-direct-P1269 ../../../../data/all/prop-direct-P112 1
./s1 ../../../../data/all/prop-direct-P1740 ../../../../data/all/prop-direct-P301 ../../../../data/all/prop-direct-P84 ../../../../data/all/prop-direct-P800 1
./s1 ../../../../data/all/prop-direct-P360 ../../../../data/all/prop-direct-P398 ../../../../data/all/prop-direct-P397 ../../../../data/all/prop-direct-P2354 1
./s1 ../../../../data/all/prop-direct-P205 ../../../../data/all/prop-direct-P1424 ../../../../data/all/prop-direct-P1423 ../../../../data/all/prop-direct-P206 1
./s1 ../../../../data/all/prop-direct-P1200 ../../../../data/all/prop-direct-P301 ../../../../data/all/prop-direct-P4614 ../../../../data/all/prop-direct-P974 1
./s1 ../../../../data/all/prop-direct-P20 ../../../../data/all/prop-direct-P127 ../../../../data/all/prop-direct-P40 ../../../../data/all/prop-direct-P25 1
./s1 ../../../../data/all/prop-direct-P1376 ../../../../data/all/prop-direct-P463 ../../../../data/all/prop-direct-P1891 ../../../../data/all/prop-direct-P20 1
./s1 ../../../../data/all/prop-direct-P159 ../../../../data/all/prop-direct-P2388 ../../../../data/all/prop-direct-P910 ../../../../data/all/prop-direct-P301 1
./s1 ../../../../data/all/prop-direct-P69 ../../../../data/all/prop-direct-P84 ../../../../data/all/prop-direct-P802 ../../../../data/all/prop-direct-P1066 1
./s1 ../../../../data/all/prop-direct-P1659 ../../../../data/all/prop-direct-P1629 ../../../../data/all/prop-direct-P1687 ../../../../data/all/prop-direct-P2302 1
./s1 ../../../../data/all/prop-direct-P375 ../../../../data/all/prop-direct-P1269 ../../../../data/all/prop-direct-P137 ../../../../data/all/prop-direct-P793 1
./s1 ../../../../data/all/prop-direct-P2670 ../../../../data/all/prop-direct-P2389 ../../../../data/all/prop-direct-P1001 ../../../../data/all/prop-direct-P208 1
./s1 ../../../../data/all/prop-direct-P3373 ../../../../data/all/prop-direct-P144 ../../../../data/all/prop-direct-P40 ../../../../data/all/prop-direct-P451 1
./s1 ../../../../data/all/prop-direct-P53 ../../../../data/all/prop-direct-P138 ../../../../data/all/prop-direct-P910 ../../../../data/all/prop-direct-P301 1
./s1 ../../../../data/all/prop-direct-P1064 ../../../../data/all/prop-direct-P1269 ../../../../data/all/prop-direct-P910 ../../../../data/all/prop-direct-P301 1
./s1 ../../../../data/all/prop-direct-P195 ../../../../data/all/prop-direct-P40 ../../../../data/all/prop-direct-P25 ../../../../data/all/prop-direct-P1830 1
./s1 ../../../../data/all/prop-direct-P1456 ../../../../data/all/prop-direct-P360 ../../../../data/all/prop-direct-P1001 ../../../../data/all/prop-direct-P36 1
./s1 ../../../../data/all/prop-direct-P286 ../../../../data/all/prop-direct-P22 ../../../../data/all/prop-direct-P40 ../../../../data/all/prop-direct-P1038 1
./s1 ../../../../data/all/prop-direct-P87 ../../../../data/all/prop-direct-P910 ../../../../data/all/prop-direct-P301 ../../../../data/all/prop-direct-P800 1
./s1 ../../../../data/all/prop-direct-P170 ../../../../data/all/prop-direct-P1049 ../../../../data/all/prop-direct-P138 ../../../../data/all/prop-direct-P1038 1
./s1 ../../../../data/all/prop-direct-P3876 ../../../../data/all/prop-direct-P4224 ../../../../data/all/prop-direct-P910 ../../../../data/all/prop-direct-P301 1
./s1 ../../../../data/all/prop-direct-P1740 ../../../../data/all/prop-direct-P301 ../../../../data/all/prop-direct-P84 ../../../../data/all/prop-direct-P800 1
./s1 ../../../../data/all/prop-direct-P184 ../../../../data/all/prop-direct-P1299 ../../../../data/all/prop-direct-P180 ../../../../data/all/prop-direct-P185 1
./s1 ../../../../data/all/prop-direct-P137 ../../../../data/all/prop-direct-P101 ../../../../data/all/prop-direct-P3095 ../../../../data/all/prop-direct-P425 1
./s1 ../../../../data/all/prop-direct-P1056 ../../../../data/all/prop-direct-P1542 ../../../../data/all/prop-direct-P828 ../../../../data/all/prop-direct-P155 1
./s1 ../../../../data/all/prop-direct-P1066 ../../../../data/all/prop-direct-P2522 ../../../../data/all/prop-direct-P710 ../../../../data/all/prop-direct-P802 1
./s1 ../../../../data/all/prop-direct-P674 ../../../../data/all/prop-direct-P108 ../../../../data/all/prop-direct-P1441 ../../../../data/all/prop-direct-P941 1
./s1 ../../../../data/all/prop-direct-P97 ../../../../data/all/prop-direct-P140 ../../../../data/all/prop-direct-P112 ../../../../data/all/prop-direct-P1038 1
./s1 ../../../../data/all/prop-direct-P1269 ../../../../data/all/prop-direct-P1889 ../../../../data/all/prop-direct-P36 ../../../../data/all/prop-direct-P2184 1
./s1 ../../../../data/all/prop-direct-P138 ../../../../data/all/prop-direct-P1200 ../../../../data/all/prop-direct-P301 ../../../../data/all/prop-direct-P4614 1
./s1 ../../../../data/all/prop-direct-P1465 ../../../../data/all/prop-direct-P4224 ../../../../data/all/prop-direct-P1343 ../../../../data/all/prop-direct-P291 1
./s1 ../../../../data/all/prop-direct-P163 ../../../../data/all/prop-direct-P180 ../../../../data/all/prop-direct-P1299 ../../../../data/all/prop-direct-P1001 1
./s1 ../../../../data/all/prop-direct-P800 ../../../../data/all/prop-direct-P98 ../../../../data/all/prop-direct-P1687 ../../../../data/all/prop-direct-P1629 1
./s1 ../../../../data/all/prop-direct-P658 ../../../../data/all/prop-direct-P175 ../../../../data/all/prop-direct-P800 ../../../../data/all/prop-direct-P156 1
./s1 ../../../../data/all/prop-direct-P200 ../../../../data/all/prop-direct-P912 ../../../../data/all/prop-direct-P706 ../../../../data/all/prop-direct-P469 1
./s1 ../../../../data/all/prop-direct-P2517 ../../../../data/all/prop-direct-P642 ../../../../data/all/prop-direct-P1424 ../../../../data/all/prop-direct-P1423 1
./s1 ../../../../data/all/prop-direct-P3578 ../../../../data/all/prop-direct-P1343 ../../../../data/all/prop-direct-P4510 ../../../../data/all/prop-direct-P3432 1
