./s2 ../../../../data/all/prop-direct-P966 ../../../../data/all/prop-direct-P3192 ../../../../data/all/prop-direct-P434 ../../../../data/all/prop-direct-P3265 1
./s2 ../../../../data/all/prop-direct-P2154 ../../../../data/all/prop-direct-P1148 ../../../../data/all/prop-direct-P1113 ../../../../data/all/prop-direct-P2437 1
./s2 ../../../../data/all/prop-direct-P2547 ../../../../data/all/prop-direct-P4511 ../../../../data/all/prop-direct-P1314 ../../../../data/all/prop-direct-P2043 1
./s2 ../../../../data/all/prop-direct-P3092 ../../../../data/all/prop-direct-P1431 ../../../../data/all/prop-direct-P40 ../../../../data/all/prop-direct-P26 1
./s2 ../../../../data/all/prop-direct-P4786 ../../../../data/all/prop-direct-P495 ../../../../data/all/prop-direct-P4516 ../../../../data/all/prop-direct-P1532 1
./s2 ../../../../data/all/prop-direct-P1598 ../../../../data/all/prop-direct-P937 ../../../../data/all/prop-direct-P22 ../../../../data/all/prop-direct-P20 1
./s2 ../../../../data/all/prop-direct-P113 ../../../../data/all/prop-direct-P159 ../../../../data/all/prop-direct-P609 ../../../../data/all/prop-direct-P276 1
./s2 ../../../../data/all/prop-direct-P2332 ../../../../data/all/prop-direct-P1412 ../../../../data/all/prop-direct-P5327 ../../../../data/all/prop-direct-P364 1
./s2 ../../../../data/all/prop-direct-P2750 ../../../../data/all/prop-direct-P937 ../../../../data/all/prop-direct-P1430 ../../../../data/all/prop-direct-P20 1
./s2 ../../../../data/all/prop-direct-P3804 ../../../../data/all/prop-direct-P364 ../../../../data/all/prop-direct-P5951 ../../../../data/all/prop-direct-P1412 1
./s2 ../../../../data/all/prop-direct-P2824 ../../../../data/all/prop-direct-P2386 ../../../../data/all/prop-direct-P3769 ../../../../data/all/prop-direct-P2067 1
./s2 ../../../../data/all/prop-direct-normalized-P352 ../../../../data/all/prop-direct-P3417 ../../../../data/all/prop-direct-P2888 ../../../../data/all/prop-direct-P935 1
./s2 ../../../../data/all/prop-direct-P4320 ../../../../data/all/prop-direct-P1132 ../../../../data/all/prop-direct-P180 ../../../../data/all/prop-direct-P2049 1
./s2 ../../../../data/all/prop-direct-P1542 ../../../../data/all/prop-direct-P425 ../../../../data/all/prop-direct-P135 ../../../../data/all/prop-direct-P140 1
./s2 ../../../../data/all/prop-direct-P1151 ../../../../data/all/prop-direct-P3417 ../../../../data/all/prop-direct-P1889 ../../../../data/all/prop-direct-P935 1
./s2 ../../../../data/all/prop-direct-P3634 ../../../../data/all/prop-direct-P2049 ../../../../data/all/prop-direct-P402 ../../../../data/all/prop-direct-P1082 1
./s2 ../../../../data/all/prop-direct-P729 ../../../../data/all/prop-direct-P176 ../../../../data/all/prop-direct-P1317 ../../../../data/all/prop-direct-P1532 1
./s2 ../../../../data/all/prop-direct-P434 ../../../../data/all/prop-direct-P3192 ../../../../data/all/prop-direct-P966 ../../../../data/all/prop-direct-P3265 1
./s2 ../../../../data/all/prop-direct-P1123 ../../../../data/all/prop-direct-P1122 ../../../../data/all/prop-direct-P1132 ../../../../data/all/prop-direct-P1339 1
./s2 ../../../../data/all/prop-direct-P3348 ../../../../data/all/prop-direct-P1412 ../../../../data/all/prop-direct-P3077 ../../../../data/all/prop-direct-P364 1
./s2 ../../../../data/all/prop-direct-P1969 ../../../../data/all/prop-direct-P551 ../../../../data/all/prop-direct-P2349 ../../../../data/all/prop-direct-P20 1
./s2 ../../../../data/all/prop-direct-P2358 ../../../../data/all/prop-direct-P935 ../../../../data/all/prop-direct-P460 ../../../../data/all/prop-direct-P1888 1
./s2 ../../../../data/all/prop-direct-P885 ../../../../data/all/prop-direct-P205 ../../../../data/all/prop-direct-P610 ../../../../data/all/prop-direct-P530 1
./s2 ../../../../data/all/prop-direct-P2755 ../../../../data/all/prop-direct-P2047 ../../../../data/all/prop-direct-P617 ../../../../data/all/prop-direct-P2043 1
./s2 ../../../../data/all/prop-direct-P3598 ../../../../data/all/prop-direct-P2067 ../../../../data/all/prop-direct-P2685 ../../../../data/all/prop-direct-P2048 1
./s2 ../../../../data/all/prop-direct-P277 ../../../../data/all/prop-direct-P737 ../../../../data/all/prop-direct-P101 ../../../../data/all/prop-direct-P800 1
./s2 ../../../../data/all/prop-direct-P1333 ../../../../data/all/prop-direct-P206 ../../../../data/all/prop-direct-P1332 ../../../../data/all/prop-direct-P706 1
./s2 ../../../../data/all/prop-direct-P962 ../../../../data/all/prop-direct-P1391 ../../../../data/all/prop-direct-P2732 ../../../../data/all/prop-direct-P1607 1
./s2 ../../../../data/all/prop-direct-P2014 ../../../../data/all/prop-direct-P364 ../../../../data/all/prop-direct-P1953 ../../../../data/all/prop-direct-P1412 1
./s2 ../../../../data/all/prop-direct-P1814 ../../../../data/all/prop-direct-P5205 ../../../../data/all/prop-direct-P296 ../../../../data/all/prop-direct-P1103 1
./s2 ../../../../data/all/prop-direct-P2435 ../../../../data/all/prop-direct-P103 ../../../../data/all/prop-direct-P4369 ../../../../data/all/prop-direct-P1412 1
./s2 ../../../../data/all/prop-direct-P1427 ../../../../data/all/prop-direct-P559 ../../../../data/all/prop-direct-P915 ../../../../data/all/prop-direct-P840 1
./s2 ../../../../data/all/prop-direct-P1410 ../../../../data/all/prop-direct-P576 ../../../../data/all/prop-direct-P1100 ../../../../data/all/prop-direct-P580 1
./s2 ../../../../data/all/prop-direct-P2388 ../../../../data/all/prop-direct-P1001 ../../../../data/all/prop-direct-P1313 ../../../../data/all/prop-direct-P1889 1
./s2 ../../../../data/all/prop-direct-P2900 ../../../../data/all/prop-direct-P123 ../../../../data/all/prop-direct-P1329 ../../../../data/all/prop-direct-P98 1
./s2 ../../../../data/all/prop-direct-P2888 ../../../../data/all/prop-direct-P688 ../../../../data/all/prop-direct-P1709 ../../../../data/all/prop-direct-P1269 1
./s2 ../../../../data/all/prop-direct-P1049 ../../../../data/all/prop-direct-P460 ../../../../data/all/prop-direct-P136 ../../../../data/all/prop-direct-P674 1
./s2 ../../../../data/all/prop-direct-P973 ../../../../data/all/prop-direct-P180 ../../../../data/all/prop-direct-normalized-P350 ../../../../data/all/prop-direct-P170 1
./s2 ../../../../data/all/prop-direct-P1334 ../../../../data/all/prop-direct-P3417 ../../../../data/all/prop-direct-P1333 ../../../../data/all/prop-direct-P935 1
./s2 ../../../../data/all/prop-direct-P5597 ../../../../data/all/prop-direct-P3222 ../../../../data/all/prop-direct-P3509 ../../../../data/all/prop-direct-P3219 1
./s2 ../../../../data/all/prop-direct-P2032 ../../../../data/all/prop-direct-P1303 ../../../../data/all/prop-direct-P3893 ../../../../data/all/prop-direct-P870 1
./s2 ../../../../data/all/prop-direct-P2440 ../../../../data/all/prop-direct-P460 ../../../../data/all/prop-direct-P4342 ../../../../data/all/prop-direct-P144 1
./s2 ../../../../data/all/prop-direct-P1466 ../../../../data/all/prop-direct-P305 ../../../../data/all/prop-direct-P3454 ../../../../data/all/prop-direct-P3984 1
./s2 ../../../../data/all/prop-direct-P1885 ../../../../data/all/prop-direct-P1037 ../../../../data/all/prop-direct-P119 ../../../../data/all/prop-direct-P39 1
./s2 ../../../../data/all/prop-direct-P5130 ../../../../data/all/prop-direct-P1889 ../../../../data/all/prop-direct-P1269 ../../../../data/all/prop-direct-P276 1
./s2 ../../../../data/all/prop-direct-P1340 ../../../../data/all/prop-direct-P937 ../../../../data/all/prop-direct-P180 ../../../../data/all/prop-direct-P1071 1
./s2 ../../../../data/all/prop-direct-P5080 ../../../../data/all/prop-direct-P40 ../../../../data/all/prop-direct-P4342 ../../../../data/all/prop-direct-P185 1
./s2 ../../../../data/all/prop-direct-P1801 ../../../../data/all/prop-direct-P69 ../../../../data/all/prop-direct-P1442 ../../../../data/all/prop-direct-P108 1
./s2 ../../../../data/all/prop-direct-P1416 ../../../../data/all/prop-direct-P485 ../../../../data/all/prop-direct-P166 ../../../../data/all/prop-direct-P69 1
./s2 ../../../../data/all/prop-direct-P1317 ../../../../data/all/prop-direct-P101 ../../../../data/all/prop-direct-P585 ../../../../data/all/prop-direct-P1269 1
