./tr2 ../../../../data/all/prop-direct-P552 ../../../../data/all/prop-direct-P461 ../../../../data/all/prop-direct-P741 0
./tr2 ../../../../data/all/prop-direct-P479 ../../../../data/all/prop-direct-P1889 ../../../../data/all/prop-direct-P1269 0
./tr2 ../../../../data/all/prop-direct-P87 ../../../../data/all/prop-direct-P136 ../../../../data/all/prop-direct-P826 0
./tr2 ../../../../data/all/prop-direct-P5841 ../../../../data/all/prop-direct-P1889 ../../../../data/all/prop-direct-P141 0
./tr2 ../../../../data/all/prop-direct-P375 ../../../../data/all/prop-direct-P495 ../../../../data/all/prop-direct-P137 0
./tr2 ../../../../data/all/prop-direct-P1343 ../../../../data/all/prop-direct-P767 ../../../../data/all/prop-direct-P3373 0
./tr2 ../../../../data/all/prop-direct-P26 ../../../../data/all/prop-direct-P1801 ../../../../data/all/prop-direct-P1442 0
./tr2 ../../../../data/all/prop-direct-P2747 ../../../../data/all/prop-direct-P1366 ../../../../data/all/prop-direct-P2363 0
./tr2 ../../../../data/all/prop-direct-P3858 ../../../../data/all/prop-direct-P1889 ../../../../data/all/prop-direct-P1424 0
./tr2 ../../../../data/all/prop-direct-P647 ../../../../data/all/prop-direct-P276 ../../../../data/all/prop-direct-P20 0
./tr2 ../../../../data/all/prop-direct-P1073 ../../../../data/all/prop-direct-P1365 ../../../../data/all/prop-direct-P1072 0
./tr2 ../../../../data/all/prop-direct-P941 ../../../../data/all/prop-direct-P103 ../../../../data/all/prop-direct-P1412 0
./tr2 ../../../../data/all/prop-direct-P741 ../../../../data/all/prop-direct-P2283 ../../../../data/all/prop-direct-P2545 0
./tr2 ../../../../data/all/prop-direct-P749 ../../../../data/all/prop-direct-P488 ../../../../data/all/prop-direct-P2388 0
./tr2 ../../../../data/all/prop-direct-P1313 ../../../../data/all/prop-direct-P1001 ../../../../data/all/prop-direct-P1366 0
./tr2 ../../../../data/all/prop-direct-P1753 ../../../../data/all/prop-direct-P1754 ../../../../data/all/prop-direct-P1889 0
./tr2 ../../../../data/all/prop-direct-P485 ../../../../data/all/prop-direct-P488 ../../../../data/all/prop-direct-P26 0
./tr2 ../../../../data/all/prop-direct-P1302 ../../../../data/all/prop-direct-P47 ../../../../data/all/prop-direct-P276 0
./tr2 ../../../../data/all/prop-direct-P552 ../../../../data/all/prop-direct-P461 ../../../../data/all/prop-direct-P741 0
./tr2 ../../../../data/all/prop-direct-P40 ../../../../data/all/prop-direct-P39 ../../../../data/all/prop-direct-P166 0
./tr2 ../../../../data/all/prop-direct-P1753 ../../../../data/all/prop-direct-P136 ../../../../data/all/prop-direct-P301 0
./tr2 ../../../../data/all/prop-direct-P176 ../../../../data/all/prop-direct-P1365 ../../../../data/all/prop-direct-P178 0
./tr2 ../../../../data/all/prop-direct-P2747 ../../../../data/all/prop-direct-P1366 ../../../../data/all/prop-direct-P2363 0
./tr2 ../../../../data/all/prop-direct-P1811 ../../../../data/all/prop-direct-P1754 ../../../../data/all/prop-direct-P910 0
./tr2 ../../../../data/all/prop-direct-P26 ../../../../data/all/prop-direct-P22 ../../../../data/all/prop-direct-P3342 0
./tr2 ../../../../data/all/prop-direct-P185 ../../../../data/all/prop-direct-P3373 ../../../../data/all/prop-direct-P40 0
./tr2 ../../../../data/all/prop-direct-P937 ../../../../data/all/prop-direct-P473 ../../../../data/all/prop-direct-P4169 0
./tr2 ../../../../data/all/prop-direct-P4614 ../../../../data/all/prop-direct-P206 ../../../../data/all/prop-direct-P200 0
./tr2 ../../../../data/all/prop-direct-P466 ../../../../data/all/prop-direct-P1532 ../../../../data/all/prop-direct-P127 0
./tr2 ../../../../data/all/prop-direct-P1080 ../../../../data/all/prop-direct-P178 ../../../../data/all/prop-direct-P170 0
./tr2 ../../../../data/all/prop-direct-P1791 ../../../../data/all/prop-direct-P4224 ../../../../data/all/prop-direct-P138 0
./tr2 ../../../../data/all/prop-direct-P1365 ../../../../data/all/prop-direct-P910 ../../../../data/all/prop-direct-P463 0
./tr2 ../../../../data/all/prop-direct-P1037 ../../../../data/all/prop-direct-P708 ../../../../data/all/prop-direct-P460 0
./tr2 ../../../../data/all/prop-direct-P1445 ../../../../data/all/prop-direct-P272 ../../../../data/all/prop-direct-P170 0
./tr2 ../../../../data/all/prop-direct-P306 ../../../../data/all/prop-direct-P460 ../../../../data/all/prop-direct-P400 0
./tr2 ../../../../data/all/prop-direct-P272 ../../../../data/all/prop-direct-P740 ../../../../data/all/prop-direct-P915 0
./tr2 ../../../../data/all/prop-direct-P1659 ../../../../data/all/prop-direct-P126 ../../../../data/all/prop-direct-P1629 0
./tr2 ../../../../data/all/prop-direct-P530 ../../../../data/all/prop-direct-P172 ../../../../data/all/prop-direct-P138 0
./tr2 ../../../../data/all/prop-direct-P248 ../../../../data/all/prop-direct-P276 ../../../../data/all/prop-direct-P611 0
./tr2 ../../../../data/all/prop-direct-P355 ../../../../data/all/prop-direct-P1056 ../../../../data/all/prop-direct-P452 0
./tr2 ../../../../data/all/prop-direct-P1196 ../../../../data/all/prop-direct-P2283 ../../../../data/all/prop-direct-P509 0
./tr2 ../../../../data/all/prop-direct-P2302 ../../../../data/all/prop-direct-P1889 ../../../../data/all/prop-direct-P1629 0
./tr2 ../../../../data/all/prop-direct-P88 ../../../../data/all/prop-direct-P127 ../../../../data/all/prop-direct-P272 0
./tr2 ../../../../data/all/prop-direct-P690 ../../../../data/all/prop-direct-P556 ../../../../data/all/prop-direct-P138 0
./tr2 ../../../../data/all/prop-direct-P1056 ../../../../data/all/prop-direct-P1972 ../../../../data/all/prop-direct-P2037 0
./tr2 ../../../../data/all/prop-direct-P3858 ../../../../data/all/prop-direct-P1889 ../../../../data/all/prop-direct-P1424 0
./tr2 ../../../../data/all/prop-direct-P126 ../../../../data/all/prop-direct-P610 ../../../../data/all/prop-direct-P559 0
./tr2 ../../../../data/all/prop-direct-P3092 ../../../../data/all/prop-direct-P737 ../../../../data/all/prop-direct-P1431 0
./tr2 ../../../../data/all/prop-direct-P3092 ../../../../data/all/prop-direct-P3342 ../../../../data/all/prop-direct-P58 0
./tr2 ../../../../data/all/prop-direct-P1026 ../../../../data/all/prop-direct-P1416 ../../../../data/all/prop-direct-P69 0
