./t2 ../../../../data/all/prop-direct-P5277 ../../../../data/all/prop-direct-P282
./t2 ../../../../data/all/prop-direct-P2101 ../../../../data/all/prop-direct-P657
./t2 ../../../../data/all/prop-direct-P1883 ../../../../data/all/prop-direct-P1263
./t2 ../../../../data/all/prop-direct-P3394 ../../../../data/all/prop-direct-P1667
./t2 ../../../../data/all/prop-direct-P2488 ../../../../data/all/prop-direct-normalized-P2581
./t2 ../../../../data/all/prop-direct-P3165 ../../../../data/all/prop-direct-P119
./t2 ../../../../data/all/prop-direct-P6056 ../../../../data/all/prop-direct-P960
./t2 ../../../../data/all/prop-direct-P1367 ../../../../data/all/prop-direct-P3956
./t2 ../../../../data/all/prop-direct-P3360 ../../../../data/all/prop-direct-P4927
./t2 ../../../../data/all/prop-direct-P2871 ../../../../data/all/prop-direct-P645
./t2 ../../../../data/all/prop-direct-P3497 ../../../../data/all/prop-direct-P156
./t2 ../../../../data/all/prop-direct-P3639 ../../../../data/all/prop-direct-normalized-P2163
./t2 ../../../../data/all/prop-direct-P1802 ../../../../data/all/prop-direct-P2006
./t2 ../../../../data/all/prop-direct-P2016 ../../../../data/all/prop-direct-P5357
./t2 ../../../../data/all/prop-direct-P402 ../../../../data/all/prop-direct-P776
./t2 ../../../../data/all/prop-direct-P3185 ../../../../data/all/prop-direct-P158
./t2 ../../../../data/all/prop-direct-P381 ../../../../data/all/prop-direct-P138
./t2 ../../../../data/all/prop-direct-P1585 ../../../../data/all/prop-direct-P3417
./t2 ../../../../data/all/prop-direct-P1030 ../../../../data/all/prop-direct-P380
./t2 ../../../../data/all/prop-direct-P351 ../../../../data/all/prop-direct-P1651
./t2 ../../../../data/all/prop-direct-P3225 ../../../../data/all/prop-direct-P841
./t2 ../../../../data/all/prop-direct-P1581 ../../../../data/all/prop-direct-P991
./t2 ../../../../data/all/prop-direct-P3880 ../../../../data/all/prop-direct-P1533
./t2 ../../../../data/all/prop-direct-P4129 ../../../../data/all/prop-direct-P1325
./t2 ../../../../data/all/prop-direct-P57 ../../../../data/all/prop-direct-P691
./t2 ../../../../data/all/prop-direct-P709 ../../../../data/all/prop-direct-normalized-P227
./t2 ../../../../data/all/prop-direct-P5680 ../../../../data/all/prop-direct-normalized-P2163
./t2 ../../../../data/all/prop-direct-P2659 ../../../../data/all/prop-direct-normalized-P227
./t2 ../../../../data/all/prop-direct-P3780 ../../../../data/all/prop-direct-P1014
./t2 ../../../../data/all/prop-direct-P2364 ../../../../data/all/prop-direct-P162
./t2 ../../../../data/all/prop-direct-P644 ../../../../data/all/prop-direct-P3329
./t2 ../../../../data/all/prop-direct-P2980 ../../../../data/all/prop-direct-P1296
./t2 ../../../../data/all/prop-direct-P5951 ../../../../data/all/prop-direct-P1986
./t2 ../../../../data/all/prop-direct-P828 ../../../../data/all/prop-direct-P1667
./t2 ../../../../data/all/prop-direct-P1799 ../../../../data/all/prop-direct-P1936
./t2 ../../../../data/all/prop-direct-P647 ../../../../data/all/prop-direct-P2728
./t2 ../../../../data/all/prop-direct-P5081 ../../../../data/all/prop-direct-P1343
./t2 ../../../../data/all/prop-direct-P427 ../../../../data/all/prop-direct-P5945
./t2 ../../../../data/all/prop-direct-P486 ../../../../data/all/prop-direct-P2213
./t2 ../../../../data/all/prop-direct-P4490 ../../../../data/all/prop-direct-P2772
./t2 ../../../../data/all/prop-direct-P2188 ../../../../data/all/prop-direct-P1038
./t2 ../../../../data/all/prop-direct-P2581 ../../../../data/all/prop-direct-P2267
./t2 ../../../../data/all/prop-direct-P5391 ../../../../data/all/prop-direct-P3018
./t2 ../../../../data/all/prop-direct-P4141 ../../../../data/all/prop-direct-P1366
./t2 ../../../../data/all/prop-direct-P5607 ../../../../data/all/prop-direct-P910
./t2 ../../../../data/all/prop-direct-P2750 ../../../../data/all/prop-direct-P51
./t2 ../../../../data/all/ontology-beta#novalue ../../../../data/all/ontology-beta#directClaim
./t2 ../../../../data/all/prop-direct-P3957 ../../../../data/all/prop-direct-P4198
./t2 ../../../../data/all/prop-direct-P461 ../../../../data/all/prop-direct-P155
./t2 ../../../../data/all/prop-direct-P1764 ../../../../data/all/prop-direct-P708