./ti2 ../../../../data/all/prop-direct-P1315 ../../../../data/all/prop-direct-P5097 ../../../../data/all/prop-direct-P1315 ../../../../data/all/prop-direct-P5097
./ti2 ../../../../data/all/prop-direct-P781 ../../../../data/all/prop-direct-P645 ../../../../data/all/prop-direct-P781 ../../../../data/all/prop-direct-P645
./ti2 ../../../../data/all/prop-direct-P1242 ../../../../data/all/prop-direct-P742 ../../../../data/all/prop-direct-P1242 ../../../../data/all/prop-direct-P742
./ti2 ../../../../data/all/prop-direct-P1483 ../../../../data/all/prop-direct-P5381 ../../../../data/all/prop-direct-P1483 ../../../../data/all/prop-direct-P5381
./ti2 ../../../../data/all/prop-direct-P366 ../../../../data/all/prop-direct-P2505 ../../../../data/all/prop-direct-P366 ../../../../data/all/prop-direct-P2505
./ti2 ../../../../data/all/prop-direct-P791 ../../../../data/all/prop-direct-P879 ../../../../data/all/prop-direct-P791 ../../../../data/all/prop-direct-P879
./ti2 ../../../../data/all/prop-direct-P381 ../../../../data/all/prop-direct-P1824 ../../../../data/all/prop-direct-P381 ../../../../data/all/prop-direct-P1824
./ti2 ../../../../data/all/prop-direct-P5604 ../../../../data/all/prop-direct-P3568 ../../../../data/all/prop-direct-P5604 ../../../../data/all/prop-direct-P3568
./ti2 ../../../../data/all/prop-direct-P429 ../../../../data/all/prop-direct-P5534 ../../../../data/all/prop-direct-P429 ../../../../data/all/prop-direct-P5534
./ti2 ../../../../data/all/prop-direct-P3329 ../../../../data/all/prop-direct-P4985 ../../../../data/all/prop-direct-P3329 ../../../../data/all/prop-direct-P4985
./ti2 ../../../../data/all/prop-direct-P2722 ../../../../data/all/prop-direct-P4120 ../../../../data/all/prop-direct-P2722 ../../../../data/all/prop-direct-P4120
./ti2 ../../../../data/all/prop-direct-P1936 ../../../../data/all/prop-direct-P3124 ../../../../data/all/prop-direct-P1936 ../../../../data/all/prop-direct-P3124
./ti2 ../../../../data/all/prop-direct-P586 ../../../../data/all/prop-direct-P2008 ../../../../data/all/prop-direct-P586 ../../../../data/all/prop-direct-P2008
./ti2 ../../../../data/all/prop-direct-P661 ../../../../data/all/prop-direct-P1886 ../../../../data/all/prop-direct-P661 ../../../../data/all/prop-direct-P1886
./ti2 ../../../../data/all/prop-direct-P2798 ../../../../data/all/prop-direct-P3765 ../../../../data/all/prop-direct-P2798 ../../../../data/all/prop-direct-P3765
./ti2 ../../../../data/all/prop-direct-P5035 ../../../../data/all/prop-direct-P2830 ../../../../data/all/prop-direct-P5035 ../../../../data/all/prop-direct-P2830
./ti2 ../../../../data/all/prop-direct-P927 ../../../../data/all/prop-direct-P138 ../../../../data/all/prop-direct-P927 ../../../../data/all/prop-direct-P138
./ti2 ../../../../data/all/prop-direct-P1441 ../../../../data/all/prop-direct-P1308 ../../../../data/all/prop-direct-P1441 ../../../../data/all/prop-direct-P1308
./ti2 ../../../../data/all/prop-direct-P4046 ../../../../data/all/prop-direct-P4525 ../../../../data/all/prop-direct-P4046 ../../../../data/all/prop-direct-P4525
./ti2 ../../../../data/all/prop-direct-P3936 ../../../../data/all/prop-direct-P1274 ../../../../data/all/prop-direct-P3936 ../../../../data/all/prop-direct-P1274
./ti2 ../../../../data/all/prop-direct-P3925 ../../../../data/all/prop-direct-P3435 ../../../../data/all/prop-direct-P3925 ../../../../data/all/prop-direct-P3435
./ti2 ../../../../data/all/prop-direct-P5343 ../../../../data/all/prop-direct-P3857 ../../../../data/all/prop-direct-P5343 ../../../../data/all/prop-direct-P3857
./ti2 ../../../../data/all/prop-direct-P3571 ../../../../data/all/prop-direct-P1976 ../../../../data/all/prop-direct-P3571 ../../../../data/all/prop-direct-P1976
./ti2 ../../../../data/all/prop-direct-P232 ../../../../data/all/prop-direct-P591 ../../../../data/all/prop-direct-P232 ../../../../data/all/prop-direct-P591
./ti2 ../../../../data/all/prop-direct-P449 ../../../../data/all/prop-direct-P264 ../../../../data/all/prop-direct-P449 ../../../../data/all/prop-direct-P264
./ti2 ../../../../data/all/prop-direct-P5966 ../../../../data/all/prop-direct-P1933 ../../../../data/all/prop-direct-P5966 ../../../../data/all/prop-direct-P1933
./ti2 ../../../../data/all/prop-direct-P4081 ../../../../data/all/prop-direct-P2447 ../../../../data/all/prop-direct-P4081 ../../../../data/all/prop-direct-P2447
./ti2 ../../../../data/all/prop-direct-P2695 ../../../../data/all/prop-direct-P1204 ../../../../data/all/prop-direct-P2695 ../../../../data/all/prop-direct-P1204
./ti2 ../../../../data/all/prop-direct-P162 ../../../../data/all/prop-direct-P676 ../../../../data/all/prop-direct-P162 ../../../../data/all/prop-direct-P676
./ti2 ../../../../data/all/prop-direct-P2684 ../../../../data/all/prop-direct-P156 ../../../../data/all/prop-direct-P2684 ../../../../data/all/prop-direct-P156
./ti2 ../../../../data/all/prop-direct-P4611 ../../../../data/all/prop-direct-P2818 ../../../../data/all/prop-direct-P4611 ../../../../data/all/prop-direct-P2818
./ti2 ../../../../data/all/prop-direct-P1036 ../../../../data/all/prop-direct-P2818 ../../../../data/all/prop-direct-P1036 ../../../../data/all/prop-direct-P2818
./ti2 ../../../../data/all/prop-direct-P2568 ../../../../data/all/prop-direct-P180 ../../../../data/all/prop-direct-P2568 ../../../../data/all/prop-direct-P180
./ti2 ../../../../data/all/prop-direct-P2369 ../../../../data/all/prop-direct-P2697 ../../../../data/all/prop-direct-P2369 ../../../../data/all/prop-direct-P2697
./ti2 ../../../../data/all/prop-direct-P4544 ../../../../data/all/prop-direct-P2188 ../../../../data/all/prop-direct-P4544 ../../../../data/all/prop-direct-P2188
./ti2 ../../../../data/all/prop-direct-P3106 ../../../../data/all/prop-direct-P5395 ../../../../data/all/prop-direct-P3106 ../../../../data/all/prop-direct-P5395
./ti2 ../../../../data/all/prop-direct-P4983 ../../../../data/all/prop-direct-P1067 ../../../../data/all/prop-direct-P4983 ../../../../data/all/prop-direct-P1067
./ti2 ../../../../data/all/prop-direct-P2595 ../../../../data/all/prop-direct-P1181 ../../../../data/all/prop-direct-P2595 ../../../../data/all/prop-direct-P1181
./ti2 ../../../../data/all/prop-direct-P1807 ../../../../data/all/prop-direct-P902 ../../../../data/all/prop-direct-P1807 ../../../../data/all/prop-direct-P902
./ti2 ../../../../data/all/prop-direct-P2549 ../../../../data/all/prop-direct-P3420 ../../../../data/all/prop-direct-P2549 ../../../../data/all/prop-direct-P3420
./ti2 ../../../../data/all/prop-direct-P1985 ../../../../data/all/prop-direct-P348 ../../../../data/all/prop-direct-P1985 ../../../../data/all/prop-direct-P348
./ti2 ../../../../data/all/prop-direct-P5273 ../../../../data/all/prop-direct-P3346 ../../../../data/all/prop-direct-P5273 ../../../../data/all/prop-direct-P3346
./ti2 ../../../../data/all/prop-direct-P2321 ../../../../data/all/prop-direct-P1269 ../../../../data/all/prop-direct-P2321 ../../../../data/all/prop-direct-P1269
./ti2 ../../../../data/all/prop-direct-P1831 ../../../../data/all/prop-direct-P1098 ../../../../data/all/prop-direct-P1831 ../../../../data/all/prop-direct-P1098
./ti2 ../../../../data/all/prop-direct-P3451 ../../../../data/all/prop-direct-P242 ../../../../data/all/prop-direct-P3451 ../../../../data/all/prop-direct-P242
./ti2 ../../../../data/all/prop-direct-P3610 ../../../../data/all/prop-direct-P47 ../../../../data/all/prop-direct-P3610 ../../../../data/all/prop-direct-P47
./ti2 ../../../../data/all/prop-direct-P4434 ../../../../data/all/prop-direct-P4728 ../../../../data/all/prop-direct-P4434 ../../../../data/all/prop-direct-P4728
./ti2 ../../../../data/all/prop-direct-P2347 ../../../../data/all/prop-direct-P617 ../../../../data/all/prop-direct-P2347 ../../../../data/all/prop-direct-P617
./ti2 ../../../../data/all/prop-direct-P4391 ../../../../data/all/prop-direct-P5407 ../../../../data/all/prop-direct-P4391 ../../../../data/all/prop-direct-P5407
./ti2 ../../../../data/all/prop-direct-P2659 ../../../../data/all/prop-direct-P1868 ../../../../data/all/prop-direct-P2659 ../../../../data/all/prop-direct-P1868
