./t3 ../../../../data/all/prop-direct-P2558 ../../../../data/all/prop-direct-P2268 ../../../../data/all/prop-direct-normalized-P269 
./t3 ../../../../data/all/prop-direct-P5383 ../../../../data/all/prop-direct-P5294 ../../../../data/all/prop-direct-P84 
./t3 ../../../../data/all/prop-direct-P1725 ../../../../data/all/prop-direct-P264 ../../../../data/all/prop-direct-P3417 
./t3 ../../../../data/all/prop-direct-P3171 ../../../../data/all/prop-direct-P3630 ../../../../data/all/prop-direct-P3509 
./t3 ../../../../data/all/prop-direct-P4728 ../../../../data/all/prop-direct-P961 ../../../../data/all/prop-direct-P5984 
./t3 ../../../../data/all/prop-direct-P1273 ../../../../data/all/prop-direct-P2704 ../../../../data/all/prop-direct-P269 
./t3 ../../../../data/all/prop-direct-P3650 ../../../../data/all/prop-direct-P1712 ../../../../data/all/prop-direct-P825 
./t3 ../../../../data/all/prop-direct-P557 ../../../../data/all/prop-direct-P962 ../../../../data/all/prop-direct-P910 
./t3 ../../../../data/all/prop-direct-P1942 ../../../../data/all/prop-direct-P127 ../../../../data/all/prop-direct-P5584 
./t3 ../../../../data/all/prop-direct-P1472 ../../../../data/all/prop-direct-P781 ../../../../data/all/prop-direct-P5597 
./t3 ../../../../data/all/prop-direct-P1746 ../../../../data/all/prop-direct-P1256 ../../../../data/all/prop-direct-P838 
./t3 ../../../../data/all/prop-direct-P2180 ../../../../data/all/prop-direct-P1309 ../../../../data/all/prop-direct-P2538 
./t3 ../../../../data/all/prop-direct-P5724 ../../../../data/all/prop-direct-P1889 ../../../../data/all/prop-direct-P3957 
./t3 ../../../../data/all/prop-direct-P3933 ../../../../data/all/prop-direct-P1545 ../../../../data/all/prop-direct-P345 
./t3 ../../../../data/all/ontology-beta#claim ../../../../data/all/prop-direct-P276 ../../../../data/all/prop-direct-P1855 
./t3 ../../../../data/all/prop-direct-normalized-P1584 ../../../../data/all/prop-direct-normalized-P592 ../../../../data/all/prop-direct-P233 
./t3 ../../../../data/all/prop-direct-P2284 ../../../../data/all/prop-direct-P968 ../../../../data/all/prop-direct-P2002 
./t3 ../../../../data/all/prop-direct-P442 ../../../../data/all/prop-direct-P949 ../../../../data/all/prop-direct-P1997 
./t3 ../../../../data/all/prop-direct-P863 ../../../../data/all/prop-direct-P3265 ../../../../data/all/prop-direct-P2174 
./t3 ../../../../data/all/prop-direct-P480 ../../../../data/all/prop-direct-P4839 ../../../../data/all/prop-direct-P1981 
./t3 ../../../../data/all/prop-direct-P683 ../../../../data/all/prop-direct-P691 ../../../../data/all/prop-direct-P2959 
./t3 ../../../../data/all/prop-direct-P4659 ../../../../data/all/prop-direct-P950 ../../../../data/all/prop-direct-P3987 
./t3 ../../../../data/all/ontology-beta#statementValueNormalized ../../../../data/all/prop-direct-P123 ../../../../data/all/ontology-beta#claim 
./t3 ../../../../data/all/prop-direct-P559 ../../../../data/all/prop-direct-P3472 ../../../../data/all/prop-direct-P2002 
./t3 ../../../../data/all/prop-direct-P4023 ../../../../data/all/prop-direct-P102 ../../../../data/all/prop-direct-P1447 
./t3 ../../../../data/all/prop-direct-P2186 ../../../../data/all/prop-direct-P2929 ../../../../data/all/prop-direct-P2980 
./t3 ../../../../data/all/prop-direct-P5381 ../../../../data/all/prop-direct-P1662 ../../../../data/all/prop-direct-P5586 
./t3 ../../../../data/all/prop-direct-P2547 ../../../../data/all/prop-direct-P3219 ../../../../data/all/prop-direct-P5130 
./t3 ../../../../data/all/prop-direct-P2180 ../../../../data/all/prop-direct-P1818 ../../../../data/all/prop-direct-P3219 
./t3 ../../../../data/all/prop-direct-P4312 ../../../../data/all/prop-direct-P162 ../../../../data/all/prop-direct-P856 
./t3 ../../../../data/all/prop-direct-P3441 ../../../../data/all/prop-direct-P3794 ../../../../data/all/prop-direct-P856 
./t3 ../../../../data/all/prop-direct-P2574 ../../../../data/all/prop-direct-P1285 ../../../../data/all/prop-direct-P3579 
./t3 ../../../../data/all/prop-direct-P5288 ../../../../data/all/prop-direct-P1814 ../../../../data/all/prop-direct-P454 
./t3 ../../../../data/all/prop-direct-P3459 ../../../../data/all/prop-direct-P181 ../../../../data/all/prop-direct-P5397 
./t3 ../../../../data/all/prop-direct-P3626 ../../../../data/all/prop-direct-P1886 ../../../../data/all/prop-direct-P3513 
./t3 ../../../../data/all/prop-direct-P575 ../../../../data/all/prop-direct-P127 ../../../../data/all/prop-direct-P1212 
./t3 ../../../../data/all/prop-direct-P5652 ../../../../data/all/prop-direct-P4169 ../../../../data/all/prop-direct-normalized-P268 
./t3 ../../../../data/all/prop-direct-P5357 ../../../../data/all/prop-direct-normalized-P1795 ../../../../data/all/prop-direct-P241 
./t3 ../../../../data/all/prop-direct-P4643 ../../../../data/all/prop-direct-normalized-P1795 ../../../../data/all/prop-direct-P1559 
./t3 ../../../../data/all/prop-direct-P20 ../../../../data/all/prop-direct-P2397 ../../../../data/all/prop-direct-P1315 
./t3 ../../../../data/all/prop-direct-P2750 ../../../../data/all/prop-direct-P1299 ../../../../data/all/prop-direct-P2268 
./t3 ../../../../data/all/prop-direct-P20 ../../../../data/all/prop-direct-P1942 ../../../../data/all/prop-direct-P2013 
./t3 ../../../../data/all/prop-direct-P3936 ../../../../data/all/prop-direct-P3940 ../../../../data/all/prop-direct-normalized-P227 
./t3 ../../../../data/all/prop-direct-P2359 ../../../../data/all/prop-direct-P3222 ../../../../data/all/prop-direct-P4629 
./t3 ../../../../data/all/prop-direct-P2040 ../../../../data/all/prop-direct-P4807 ../../../../data/all/prop-direct-P1403 
./t3 ../../../../data/all/prop-direct-P1989 ../../../../data/all/prop-direct-P2003 ../../../../data/all/prop-direct-P244 
./t3 ../../../../data/all/prop-direct-P5800 ../../../../data/all/prop-direct-P26 ../../../../data/all/prop-direct-P512 
./t3 ../../../../data/all/prop-direct-P1045 ../../../../data/all/prop-direct-P2383 ../../../../data/all/prop-direct-P4223 
./t3 ../../../../data/all/prop-direct-P1093 ../../../../data/all/prop-direct-P2980 ../../../../data/all/prop-direct-normalized-P227 
./t3 ../../../../data/all/prop-direct-P1651 ../../../../data/all/prop-direct-P553 ../../../../data/all/prop-direct-P856