./p2 ../../../../data/all/prop-direct-P485 ../../../../data/all/prop-direct-P1449 ../../../../data/priorities/pri1 ../../../../data/priorities/pri2 0 1
./p2 ../../../../data/all/prop-direct-P1080 ../../../../data/all/prop-direct-P1256 ../../../../data/priorities/pri1 ../../../../data/priorities/pri2 0 1
./p2 ../../../../data/all/prop-direct-P155 ../../../../data/all/prop-direct-P3473 ../../../../data/priorities/pri1 ../../../../data/priorities/pri2 0 1
./p2 ../../../../data/all/prop-direct-P4195 ../../../../data/all/prop-direct-P360 ../../../../data/priorities/pri1 ../../../../data/priorities/pri2 0 1
./p2 ../../../../data/all/prop-direct-P16 ../../../../data/all/prop-direct-P36 ../../../../data/priorities/pri1 ../../../../data/priorities/pri2 0 1
./p2 ../../../../data/all/prop-direct-P559 ../../../../data/all/prop-direct-P2130 ../../../../data/priorities/pri1 ../../../../data/priorities/pri2 0 1
./p2 ../../../../data/all/prop-direct-P1412 ../../../../data/all/prop-direct-P3219 ../../../../data/priorities/pri1 ../../../../data/priorities/pri2 0 1
./p2 ../../../../data/all/prop-direct-P2548 ../../../../data/all/prop-direct-P1889 ../../../../data/priorities/pri1 ../../../../data/priorities/pri2 0 1
./p2 ../../../../data/all/prop-direct-P5277 ../../../../data/all/prop-direct-P3417 ../../../../data/priorities/pri1 ../../../../data/priorities/pri2 0 1
./p2 ../../../../data/all/prop-direct-P86 ../../../../data/all/prop-direct-P2886 ../../../../data/priorities/pri1 ../../../../data/priorities/pri2 0 1
./p2 ../../../../data/all/prop-direct-P175 ../../../../data/all/prop-direct-P2581 ../../../../data/priorities/pri1 ../../../../data/priorities/pri2 0 1
./p2 ../../../../data/all/prop-direct-P30 ../../../../data/all/prop-direct-P1465 ../../../../data/priorities/pri1 ../../../../data/priorities/pri2 0 1
./p2 ../../../../data/all/prop-direct-P647 ../../../../data/all/prop-direct-P910 ../../../../data/priorities/pri1 ../../../../data/priorities/pri2 0 1
./p2 ../../../../data/all/prop-direct-P1753 ../../../../data/all/prop-direct-P149 ../../../../data/priorities/pri1 ../../../../data/priorities/pri2 0 1
./p2 ../../../../data/all/prop-direct-P282 ../../../../data/all/prop-direct-P3916 ../../../../data/priorities/pri1 ../../../../data/priorities/pri2 0 1
./p2 ../../../../data/all/prop-direct-P196 ../../../../data/all/prop-direct-P1014 ../../../../data/priorities/pri1 ../../../../data/priorities/pri2 0 1
./p2 ../../../../data/all/prop-direct-P6 ../../../../data/all/prop-direct-P2522 ../../../../data/priorities/pri1 ../../../../data/priorities/pri2 0 1
./p2 ../../../../data/all/prop-direct-P3578 ../../../../data/all/prop-direct-P486 ../../../../data/priorities/pri1 ../../../../data/priorities/pri2 0 1
./p2 ../../../../data/all/prop-direct-P1038 ../../../../data/all/prop-direct-P5284 ../../../../data/priorities/pri1 ../../../../data/priorities/pri2 0 1
./p2 ../../../../data/all/prop-direct-P853 ../../../../data/all/prop-direct-P2354 ../../../../data/priorities/pri1 ../../../../data/priorities/pri2 0 1
./p2 ../../../../data/all/prop-direct-P1302 ../../../../data/all/prop-direct-P782 ../../../../data/priorities/pri1 ../../../../data/priorities/pri2 0 1
./p2 ../../../../data/all/prop-direct-P176 ../../../../data/all/prop-direct-P2174 ../../../../data/priorities/pri1 ../../../../data/priorities/pri2 0 1
./p2 ../../../../data/all/prop-direct-P4608 ../../../../data/all/prop-direct-P2722 ../../../../data/priorities/pri1 ../../../../data/priorities/pri2 0 1
./p2 ../../../../data/all/prop-direct-P39 ../../../../data/all/prop-direct-P998 ../../../../data/priorities/pri1 ../../../../data/priorities/pri2 0 1
./p2 ../../../../data/all/prop-direct-P556 ../../../../data/all/prop-direct-P3219 ../../../../data/priorities/pri1 ../../../../data/priorities/pri2 0 1
./p2 ../../../../data/all/prop-direct-P4952 ../../../../data/all/prop-direct-P123 ../../../../data/priorities/pri1 ../../../../data/priorities/pri2 0 1
./p2 ../../../../data/all/prop-direct-P2517 ../../../../data/all/prop-direct-P910 ../../../../data/priorities/pri1 ../../../../data/priorities/pri2 0 1
./p2 ../../../../data/all/prop-direct-P826 ../../../../data/all/prop-direct-P461 ../../../../data/priorities/pri1 ../../../../data/priorities/pri2 0 1
./p2 ../../../../data/all/prop-direct-P1875 ../../../../data/all/prop-direct-P488 ../../../../data/priorities/pri1 ../../../../data/priorities/pri2 0 1
./p2 ../../../../data/all/prop-direct-P974 ../../../../data/all/prop-direct-P5383 ../../../../data/priorities/pri1 ../../../../data/priorities/pri2 0 1
./p2 ../../../../data/all/prop-direct-P376 ../../../../data/all/prop-direct-P948 ../../../../data/priorities/pri1 ../../../../data/priorities/pri2 0 1
./p2 ../../../../data/all/prop-direct-P3780 ../../../../data/all/prop-direct-P1036 ../../../../data/priorities/pri1 ../../../../data/priorities/pri2 0 1
./p2 ../../../../data/all/prop-direct-P483 ../../../../data/all/prop-direct-P1424 ../../../../data/priorities/pri1 ../../../../data/priorities/pri2 0 1
./p2 ../../../../data/all/prop-direct-P553 ../../../../data/all/prop-direct-P170 ../../../../data/priorities/pri1 ../../../../data/priorities/pri2 0 1
./p2 ../../../../data/all/prop-direct-P2408 ../../../../data/all/prop-direct-P4223 ../../../../data/priorities/pri1 ../../../../data/priorities/pri2 0 1
./p2 ../../../../data/all/prop-direct-P179 ../../../../data/all/prop-direct-P1376 ../../../../data/priorities/pri1 ../../../../data/priorities/pri2 0 1
./p2 ../../../../data/all/prop-direct-P841 ../../../../data/all/prop-direct-P2184 ../../../../data/priorities/pri1 ../../../../data/priorities/pri2 0 1
./p2 ../../../../data/all/prop-direct-P741 ../../../../data/all/prop-direct-P487 ../../../../data/priorities/pri1 ../../../../data/priorities/pri2 0 1
./p2 ../../../../data/all/prop-direct-P1066 ../../../../data/all/prop-direct-P4042 ../../../../data/priorities/pri1 ../../../../data/priorities/pri2 0 1
./p2 ../../../../data/all/prop-direct-P282 ../../../../data/all/prop-direct-normalized-P2581 ../../../../data/priorities/pri1 ../../../../data/priorities/pri2 0 1
./p2 ../../../../data/all/prop-direct-P1427 ../../../../data/all/prop-direct-P4431 ../../../../data/priorities/pri1 ../../../../data/priorities/pri2 0 1
./p2 ../../../../data/all/prop-direct-P674 ../../../../data/all/prop-direct-P241 ../../../../data/priorities/pri1 ../../../../data/priorities/pri2 0 1
./p2 ../../../../data/all/prop-direct-P5105 ../../../../data/all/prop-direct-P2354 ../../../../data/priorities/pri1 ../../../../data/priorities/pri2 0 1
./p2 ../../../../data/all/prop-direct-P5277 ../../../../data/all/prop-direct-P910 ../../../../data/priorities/pri1 ../../../../data/priorities/pri2 0 1
./p2 ../../../../data/all/prop-direct-P4614 ../../../../data/all/prop-direct-P3643 ../../../../data/priorities/pri1 ../../../../data/priorities/pri2 0 1
./p2 ../../../../data/all/prop-direct-P1884 ../../../../data/all/prop-direct-P1843 ../../../../data/priorities/pri1 ../../../../data/priorities/pri2 0 1
./p2 ../../../../data/all/prop-direct-P509 ../../../../data/all/prop-direct-P1375 ../../../../data/priorities/pri1 ../../../../data/priorities/pri2 0 1
./p2 ../../../../data/all/prop-direct-P5130 ../../../../data/all/prop-direct-P463 ../../../../data/priorities/pri1 ../../../../data/priorities/pri2 0 1
./p2 ../../../../data/all/prop-direct-P3578 ../../../../data/all/prop-direct-P5166 ../../../../data/priorities/pri1 ../../../../data/priorities/pri2 0 1
./p2 ../../../../data/all/prop-direct-P2388 ../../../../data/all/prop-direct-P1269 ../../../../data/priorities/pri1 ../../../../data/priorities/pri2 0 1
