./t2 ../../../../data/all/prop-direct-P5277 ../../../../data/all/prop-direct-P282 ../../../../data/priorities/pri1 ../../../../data/priorities/pri2 0 1
./t2 ../../../../data/all/prop-direct-P2101 ../../../../data/all/prop-direct-P657 ../../../../data/priorities/pri1 ../../../../data/priorities/pri2 0 1
./t2 ../../../../data/all/prop-direct-P1883 ../../../../data/all/prop-direct-P1263 ../../../../data/priorities/pri1 ../../../../data/priorities/pri2 0 1
./t2 ../../../../data/all/prop-direct-P3394 ../../../../data/all/prop-direct-P1667 ../../../../data/priorities/pri1 ../../../../data/priorities/pri2 0 1
./t2 ../../../../data/all/prop-direct-P2488 ../../../../data/all/prop-direct-normalized-P2581 ../../../../data/priorities/pri1 ../../../../data/priorities/pri2 0 1
./t2 ../../../../data/all/prop-direct-P3165 ../../../../data/all/prop-direct-P119 ../../../../data/priorities/pri1 ../../../../data/priorities/pri2 0 1
./t2 ../../../../data/all/prop-direct-P6056 ../../../../data/all/prop-direct-P960 ../../../../data/priorities/pri1 ../../../../data/priorities/pri2 0 1
./t2 ../../../../data/all/prop-direct-P1367 ../../../../data/all/prop-direct-P3956 ../../../../data/priorities/pri1 ../../../../data/priorities/pri2 0 1
./t2 ../../../../data/all/prop-direct-P3360 ../../../../data/all/prop-direct-P4927 ../../../../data/priorities/pri1 ../../../../data/priorities/pri2 0 1
./t2 ../../../../data/all/prop-direct-P2871 ../../../../data/all/prop-direct-P645 ../../../../data/priorities/pri1 ../../../../data/priorities/pri2 0 1
./t2 ../../../../data/all/prop-direct-P3497 ../../../../data/all/prop-direct-P156 ../../../../data/priorities/pri1 ../../../../data/priorities/pri2 0 1
./t2 ../../../../data/all/prop-direct-P3639 ../../../../data/all/prop-direct-normalized-P2163 ../../../../data/priorities/pri1 ../../../../data/priorities/pri2 0 1
./t2 ../../../../data/all/prop-direct-P1802 ../../../../data/all/prop-direct-P2006 ../../../../data/priorities/pri1 ../../../../data/priorities/pri2 0 1
./t2 ../../../../data/all/prop-direct-P2016 ../../../../data/all/prop-direct-P5357 ../../../../data/priorities/pri1 ../../../../data/priorities/pri2 0 1
./t2 ../../../../data/all/prop-direct-P402 ../../../../data/all/prop-direct-P776 ../../../../data/priorities/pri1 ../../../../data/priorities/pri2 0 1
./t2 ../../../../data/all/prop-direct-P3185 ../../../../data/all/prop-direct-P158 ../../../../data/priorities/pri1 ../../../../data/priorities/pri2 0 1
./t2 ../../../../data/all/prop-direct-P381 ../../../../data/all/prop-direct-P138 ../../../../data/priorities/pri1 ../../../../data/priorities/pri2 0 1
./t2 ../../../../data/all/prop-direct-P1585 ../../../../data/all/prop-direct-P3417 ../../../../data/priorities/pri1 ../../../../data/priorities/pri2 0 1
./t2 ../../../../data/all/prop-direct-P1030 ../../../../data/all/prop-direct-P380 ../../../../data/priorities/pri1 ../../../../data/priorities/pri2 0 1
./t2 ../../../../data/all/prop-direct-P351 ../../../../data/all/prop-direct-P1651 ../../../../data/priorities/pri1 ../../../../data/priorities/pri2 0 1
./t2 ../../../../data/all/prop-direct-P3225 ../../../../data/all/prop-direct-P841 ../../../../data/priorities/pri1 ../../../../data/priorities/pri2 0 1
./t2 ../../../../data/all/prop-direct-P1581 ../../../../data/all/prop-direct-P991 ../../../../data/priorities/pri1 ../../../../data/priorities/pri2 0 1
./t2 ../../../../data/all/prop-direct-P3880 ../../../../data/all/prop-direct-P1533 ../../../../data/priorities/pri1 ../../../../data/priorities/pri2 0 1
./t2 ../../../../data/all/prop-direct-P4129 ../../../../data/all/prop-direct-P1325 ../../../../data/priorities/pri1 ../../../../data/priorities/pri2 0 1
./t2 ../../../../data/all/prop-direct-P57 ../../../../data/all/prop-direct-P691 ../../../../data/priorities/pri1 ../../../../data/priorities/pri2 0 1
./t2 ../../../../data/all/prop-direct-P709 ../../../../data/all/prop-direct-normalized-P227 ../../../../data/priorities/pri1 ../../../../data/priorities/pri2 0 1
./t2 ../../../../data/all/prop-direct-P5680 ../../../../data/all/prop-direct-normalized-P2163 ../../../../data/priorities/pri1 ../../../../data/priorities/pri2 0 1
./t2 ../../../../data/all/prop-direct-P2659 ../../../../data/all/prop-direct-normalized-P227 ../../../../data/priorities/pri1 ../../../../data/priorities/pri2 0 1
./t2 ../../../../data/all/prop-direct-P3780 ../../../../data/all/prop-direct-P1014 ../../../../data/priorities/pri1 ../../../../data/priorities/pri2 0 1
./t2 ../../../../data/all/prop-direct-P2364 ../../../../data/all/prop-direct-P162 ../../../../data/priorities/pri1 ../../../../data/priorities/pri2 0 1
./t2 ../../../../data/all/prop-direct-P644 ../../../../data/all/prop-direct-P3329 ../../../../data/priorities/pri1 ../../../../data/priorities/pri2 0 1
./t2 ../../../../data/all/prop-direct-P2980 ../../../../data/all/prop-direct-P1296 ../../../../data/priorities/pri1 ../../../../data/priorities/pri2 0 1
./t2 ../../../../data/all/prop-direct-P5951 ../../../../data/all/prop-direct-P1986 ../../../../data/priorities/pri1 ../../../../data/priorities/pri2 0 1
./t2 ../../../../data/all/prop-direct-P828 ../../../../data/all/prop-direct-P1667 ../../../../data/priorities/pri1 ../../../../data/priorities/pri2 0 1
./t2 ../../../../data/all/prop-direct-P1799 ../../../../data/all/prop-direct-P1936 ../../../../data/priorities/pri1 ../../../../data/priorities/pri2 0 1
./t2 ../../../../data/all/prop-direct-P647 ../../../../data/all/prop-direct-P2728 ../../../../data/priorities/pri1 ../../../../data/priorities/pri2 0 1
./t2 ../../../../data/all/prop-direct-P5081 ../../../../data/all/prop-direct-P1343 ../../../../data/priorities/pri1 ../../../../data/priorities/pri2 0 1
./t2 ../../../../data/all/prop-direct-P427 ../../../../data/all/prop-direct-P5945 ../../../../data/priorities/pri1 ../../../../data/priorities/pri2 0 1
./t2 ../../../../data/all/prop-direct-P486 ../../../../data/all/prop-direct-P2213 ../../../../data/priorities/pri1 ../../../../data/priorities/pri2 0 1
./t2 ../../../../data/all/prop-direct-P4490 ../../../../data/all/prop-direct-P2772 ../../../../data/priorities/pri1 ../../../../data/priorities/pri2 0 1
./t2 ../../../../data/all/prop-direct-P2188 ../../../../data/all/prop-direct-P1038 ../../../../data/priorities/pri1 ../../../../data/priorities/pri2 0 1
./t2 ../../../../data/all/prop-direct-P2581 ../../../../data/all/prop-direct-P2267 ../../../../data/priorities/pri1 ../../../../data/priorities/pri2 0 1
./t2 ../../../../data/all/prop-direct-P5391 ../../../../data/all/prop-direct-P3018 ../../../../data/priorities/pri1 ../../../../data/priorities/pri2 0 1
./t2 ../../../../data/all/prop-direct-P4141 ../../../../data/all/prop-direct-P1366 ../../../../data/priorities/pri1 ../../../../data/priorities/pri2 0 1
./t2 ../../../../data/all/prop-direct-P5607 ../../../../data/all/prop-direct-P910 ../../../../data/priorities/pri1 ../../../../data/priorities/pri2 0 1
./t2 ../../../../data/all/prop-direct-P2750 ../../../../data/all/prop-direct-P51 ../../../../data/priorities/pri1 ../../../../data/priorities/pri2 0 1
./t2 ../../../../data/all/ontology-beta#novalue ../../../../data/all/ontology-beta#directClaim ../../../../data/priorities/pri1 ../../../../data/priorities/pri2 0 1
./t2 ../../../../data/all/prop-direct-P3957 ../../../../data/all/prop-direct-P4198 ../../../../data/priorities/pri1 ../../../../data/priorities/pri2 0 1
./t2 ../../../../data/all/prop-direct-P461 ../../../../data/all/prop-direct-P155 ../../../../data/priorities/pri1 ../../../../data/priorities/pri2 0 1
./t2 ../../../../data/all/prop-direct-P1764 ../../../../data/all/prop-direct-P708 ../../../../data/priorities/pri1 ../../../../data/priorities/pri2 0 1
