./p2 ../../../../data/all/prop-direct-P485 ../../../../data/all/prop-direct-P1449
./p2 ../../../../data/all/prop-direct-P1080 ../../../../data/all/prop-direct-P1256
./p2 ../../../../data/all/prop-direct-P155 ../../../../data/all/prop-direct-P3473
./p2 ../../../../data/all/prop-direct-P4195 ../../../../data/all/prop-direct-P360
./p2 ../../../../data/all/prop-direct-P16 ../../../../data/all/prop-direct-P36
./p2 ../../../../data/all/prop-direct-P559 ../../../../data/all/prop-direct-P2130
./p2 ../../../../data/all/prop-direct-P1412 ../../../../data/all/prop-direct-P3219
./p2 ../../../../data/all/prop-direct-P2548 ../../../../data/all/prop-direct-P1889
./p2 ../../../../data/all/prop-direct-P5277 ../../../../data/all/prop-direct-P3417
./p2 ../../../../data/all/prop-direct-P86 ../../../../data/all/prop-direct-P2886
./p2 ../../../../data/all/prop-direct-P175 ../../../../data/all/prop-direct-P2581
./p2 ../../../../data/all/prop-direct-P30 ../../../../data/all/prop-direct-P1465
./p2 ../../../../data/all/prop-direct-P647 ../../../../data/all/prop-direct-P910
./p2 ../../../../data/all/prop-direct-P1753 ../../../../data/all/prop-direct-P149
./p2 ../../../../data/all/prop-direct-P282 ../../../../data/all/prop-direct-P3916
./p2 ../../../../data/all/prop-direct-P196 ../../../../data/all/prop-direct-P1014
./p2 ../../../../data/all/prop-direct-P6 ../../../../data/all/prop-direct-P2522
./p2 ../../../../data/all/prop-direct-P3578 ../../../../data/all/prop-direct-P486
./p2 ../../../../data/all/prop-direct-P1038 ../../../../data/all/prop-direct-P5284
./p2 ../../../../data/all/prop-direct-P853 ../../../../data/all/prop-direct-P2354
./p2 ../../../../data/all/prop-direct-P1302 ../../../../data/all/prop-direct-P782
./p2 ../../../../data/all/prop-direct-P176 ../../../../data/all/prop-direct-P2174
./p2 ../../../../data/all/prop-direct-P4608 ../../../../data/all/prop-direct-P2722
./p2 ../../../../data/all/prop-direct-P39 ../../../../data/all/prop-direct-P998
./p2 ../../../../data/all/prop-direct-P556 ../../../../data/all/prop-direct-P3219
./p2 ../../../../data/all/prop-direct-P4952 ../../../../data/all/prop-direct-P123
./p2 ../../../../data/all/prop-direct-P2517 ../../../../data/all/prop-direct-P910
./p2 ../../../../data/all/prop-direct-P826 ../../../../data/all/prop-direct-P461
./p2 ../../../../data/all/prop-direct-P1875 ../../../../data/all/prop-direct-P488
./p2 ../../../../data/all/prop-direct-P974 ../../../../data/all/prop-direct-P5383
./p2 ../../../../data/all/prop-direct-P376 ../../../../data/all/prop-direct-P948
./p2 ../../../../data/all/prop-direct-P3780 ../../../../data/all/prop-direct-P1036
./p2 ../../../../data/all/prop-direct-P483 ../../../../data/all/prop-direct-P1424
./p2 ../../../../data/all/prop-direct-P553 ../../../../data/all/prop-direct-P170
./p2 ../../../../data/all/prop-direct-P2408 ../../../../data/all/prop-direct-P4223
./p2 ../../../../data/all/prop-direct-P179 ../../../../data/all/prop-direct-P1376
./p2 ../../../../data/all/prop-direct-P841 ../../../../data/all/prop-direct-P2184
./p2 ../../../../data/all/prop-direct-P741 ../../../../data/all/prop-direct-P487
./p2 ../../../../data/all/prop-direct-P1066 ../../../../data/all/prop-direct-P4042
./p2 ../../../../data/all/prop-direct-P282 ../../../../data/all/prop-direct-normalized-P2581
./p2 ../../../../data/all/prop-direct-P1427 ../../../../data/all/prop-direct-P4431
./p2 ../../../../data/all/prop-direct-P674 ../../../../data/all/prop-direct-P241
./p2 ../../../../data/all/prop-direct-P5105 ../../../../data/all/prop-direct-P2354
./p2 ../../../../data/all/prop-direct-P5277 ../../../../data/all/prop-direct-P910
./p2 ../../../../data/all/prop-direct-P4614 ../../../../data/all/prop-direct-P3643
./p2 ../../../../data/all/prop-direct-P1884 ../../../../data/all/prop-direct-P1843
./p2 ../../../../data/all/prop-direct-P509 ../../../../data/all/prop-direct-P1375
./p2 ../../../../data/all/prop-direct-P5130 ../../../../data/all/prop-direct-P463
./p2 ../../../../data/all/prop-direct-P3578 ../../../../data/all/prop-direct-P5166
./p2 ../../../../data/all/prop-direct-P2388 ../../../../data/all/prop-direct-P1269
