./t4 ../../../../data/all/prop-direct-P1725 ../../../../data/all/prop-direct-P2205 ../../../../data/all/prop-direct-P437 ../../../../data/all/prop-direct-P264
./t4 ../../../../data/all/prop-direct-P1351 ../../../../data/all/prop-direct-P1477 ../../../../data/all/prop-direct-P1412 ../../../../data/all/prop-direct-P2574
./t4 ../../../../data/all/prop-direct-P4673 ../../../../data/all/prop-direct-P4144 ../../../../data/all/prop-direct-P217 ../../../../data/all/prop-direct-P276
./t4 ../../../../data/all/prop-direct-P5108 ../../../../data/all/prop-direct-P2047 ../../../../data/all/prop-direct-P5099 ../../../../data/all/prop-direct-P3868
./t4 ../../../../data/all/prop-direct-P930 ../../../../data/all/prop-direct-P954 ../../../../data/all/prop-direct-P856 ../../../../data/all/prop-direct-P1064
./t4 ../../../../data/all/prop-direct-P1382 ../../../../data/all/prop-direct-P649 ../../../../data/all/prop-direct-P2596 ../../../../data/all/prop-direct-P276
./t4 ../../../../data/all/prop-direct-P714 ../../../../data/all/prop-direct-P189 ../../../../data/all/prop-direct-P579 ../../../../data/all/prop-direct-P713
./t4 ../../../../data/all/prop-direct-P1312 ../../../../data/all/prop-direct-P1036 ../../../../data/all/prop-direct-P2812 ../../../../data/all/prop-direct-P910
./t4 ../../../../data/all/prop-direct-P3227 ../../../../data/all/prop-direct-P186 ../../../../data/all/prop-direct-P177 ../../../../data/all/prop-direct-P2043
./t4 ../../../../data/all/prop-direct-P2755 ../../../../data/all/prop-direct-P2638 ../../../../data/all/prop-direct-P5032 ../../../../data/all/prop-direct-P144
./t4 ../../../../data/all/prop-direct-P1186 ../../../../data/all/prop-direct-P2963 ../../../../data/all/prop-direct-P345 ../../../../data/all/prop-direct-P39
./t4 ../../../../data/all/prop-direct-P1542 ../../../../data/all/prop-direct-P4000 ../../../../data/all/prop-direct-normalized-P961 ../../../../data/all/prop-direct-P5179
./t4 ../../../../data/all/prop-direct-P4786 ../../../../data/all/prop-direct-P179 ../../../../data/all/prop-direct-P2465 ../../../../data/all/prop-direct-P2515
./t4 ../../../../data/all/prop-direct-P4501 ../../../../data/all/prop-direct-P716 ../../../../data/all/prop-direct-P2213 ../../../../data/all/prop-direct-P397
./t4 ../../../../data/all/prop-direct-P179 ../../../../data/all/prop-direct-P580 ../../../../data/all/prop-direct-P2529 ../../../../data/all/prop-direct-P4665
./t4 ../../../../data/all/prop-direct-P2870 ../../../../data/all/prop-direct-P688 ../../../../data/all/prop-direct-P702 ../../../../data/all/prop-direct-P644
./t4 ../../../../data/all/prop-direct-P393 ../../../../data/all/prop-direct-P162 ../../../../data/all/prop-direct-normalized-P2671 ../../../../data/all/prop-direct-P495
./t4 ../../../../data/all/prop-direct-P1421 ../../../../data/all/prop-direct-P10 ../../../../data/all/prop-direct-P3151 ../../../../data/all/prop-direct-P960
./t4 ../../../../data/all/prop-direct-P3284 ../../../../data/all/prop-direct-P166 ../../../../data/all/prop-direct-P1969 ../../../../data/all/prop-direct-P2626
./t4 ../../../../data/all/prop-direct-P1586 ../../../../data/all/prop-direct-P2348 ../../../../data/all/prop-direct-P808 ../../../../data/all/prop-direct-P136
./t4 ../../../../data/all/prop-direct-P3043 ../../../../data/all/prop-direct-P898 ../../../../data/all/prop-direct-P3537 ../../../../data/all/prop-direct-P1412
./t4 ../../../../data/all/prop-direct-P364 ../../../../data/all/prop-direct-P968 ../../../../data/all/prop-direct-P449 ../../../../data/all/prop-direct-P144
./t4 ../../../../data/all/prop-direct-P477 ../../../../data/all/prop-direct-P2581 ../../../../data/all/prop-direct-P2049 ../../../../data/all/prop-direct-P1314
./t4 ../../../../data/all/prop-direct-P232 ../../../../data/all/prop-direct-P234 ../../../../data/all/prop-direct-P679 ../../../../data/all/prop-direct-P638
./t4 ../../../../data/all/prop-direct-P2722 ../../../../data/all/prop-direct-P5395 ../../../../data/all/prop-direct-normalized-P950 ../../../../data/all/prop-direct-P2168
./t4 ../../../../data/all/prop-direct-P716 ../../../../data/all/prop-direct-P2049 ../../../../data/all/prop-direct-P2054 ../../../../data/all/prop-direct-P1457
./t4 ../../../../data/all/prop-direct-normalized-P1667 ../../../../data/all/prop-direct-P1850 ../../../../data/all/prop-direct-P3417 ../../../../data/all/prop-direct-P948
./t4 ../../../../data/all/prop-direct-P3309 ../../../../data/all/prop-direct-P2347 ../../../../data/all/prop-direct-P1711 ../../../../data/all/prop-direct-P3106
./t4 ../../../../data/all/prop-direct-P2695 ../../../../data/all/prop-direct-P231 ../../../../data/all/prop-direct-P233 ../../../../data/all/prop-direct-P652
./t4 ../../../../data/all/prop-direct-P937 ../../../../data/all/prop-direct-P947 ../../../../data/all/prop-direct-P509 ../../../../data/all/prop-direct-P3435
./t4 ../../../../data/all/prop-direct-P1977 ../../../../data/all/prop-direct-P1896 ../../../../data/all/prop-direct-P2163 ../../../../data/all/prop-direct-P434
./t4 ../../../../data/all/prop-direct-P3853 ../../../../data/all/prop-direct-P644 ../../../../data/all/prop-direct-P1057 ../../../../data/all/prop-direct-P639
./t4 ../../../../data/all/prop-direct-P1793 ../../../../data/all/prop-direct-P2959 ../../../../data/all/prop-direct-P910 ../../../../data/all/prop-direct-P5398
./t4 ../../../../data/all/prop-direct-P425 ../../../../data/all/prop-direct-normalized-P2163 ../../../../data/all/prop-direct-P269 ../../../../data/all/prop-direct-P3417
./t4 ../../../../data/all/prop-direct-P3225 ../../../../data/all/prop-direct-P3794 ../../../../data/all/prop-direct-P1128 ../../../../data/all/prop-direct-P1315
#./t4 ../../../../data/all/prop-direct-P838 ../../../../data/all/prop-direct-P1939 ../../../../data/all/prop-direct-P3088 ../../../../data/all/prop-direct-P4630
./t4 ../../../../data/all/prop-direct-P1389 ../../../../data/all/prop-direct-normalized-P227 ../../../../data/all/prop-direct-P227 ../../../../data/all/prop-direct-P1417
./t4 ../../../../data/all/prop-direct-P3454 ../../../../data/all/prop-direct-P112 ../../../../data/all/prop-direct-P1414 ../../../../data/all/prop-direct-P1972
./t4 ../../../../data/all/prop-direct-P1952 ../../../../data/all/prop-direct-P39 ../../../../data/all/prop-direct-P1412 ../../../../data/all/prop-direct-P463
./t4 ../../../../data/all/prop-direct-P5271 ../../../../data/all/prop-direct-P2191 ../../../../data/all/prop-direct-P268 ../../../../data/all/prop-direct-P866
./t4 ../../../../data/all/prop-direct-P5324 ../../../../data/all/prop-direct-P3782 ../../../../data/all/prop-direct-P3154 ../../../../data/all/prop-direct-P4819
./t4 ../../../../data/all/prop-direct-P439 ../../../../data/all/prop-direct-P757 ../../../../data/all/prop-direct-P2002 ../../../../data/all/prop-direct-P268
./t4 ../../../../data/all/prop-direct-P2389 ../../../../data/all/prop-direct-P1014 ../../../../data/all/prop-direct-P2354 ../../../../data/all/prop-direct-P227
./t4 ../../../../data/all/prop-direct-normalized-P648 ../../../../data/all/prop-direct-P3532 ../../../../data/all/prop-direct-P2163 ../../../../data/all/prop-direct-P691
./t4 ../../../../data/all/prop-direct-P2747 ../../../../data/all/prop-direct-P1424 ../../../../data/all/prop-direct-P57 ../../../../data/all/prop-direct-P144
./t4 ../../../../data/all/prop-direct-P6030 ../../../../data/all/prop-direct-P3420 ../../../../data/all/prop-direct-P815 ../../../../data/all/prop-direct-P141
./t4 ../../../../data/all/prop-direct-P231 ../../../../data/all/prop-direct-normalized-P486 ../../../../data/all/prop-direct-P1542 ../../../../data/all/prop-direct-P769
./t4 ../../../../data/all/prop-direct-P591 ../../../../data/all/prop-direct-P575 ../../../../data/all/prop-direct-normalized-P1014 ../../../../data/all/prop-direct-P231
./t4 ../../../../data/all/prop-direct-P282 ../../../../data/all/prop-direct-P935 ../../../../data/all/prop-direct-P194 ../../../../data/all/prop-direct-P402
./t4 ../../../../data/all/prop-direct-P3420 ../../../../data/all/prop-direct-P1036 ../../../../data/all/prop-direct-P1745 ../../../../data/all/prop-direct-P4728