./p2 ../../../../../data/all/prop-direct-P1412 ../../../../../data/all/prop-direct-P3219
./p2 ../../../../../data/all/prop-direct-P2548 ../../../../../data/all/prop-direct-P1889
./p2 ../../../../../data/all/prop-direct-P5277 ../../../../../data/all/prop-direct-P3417
./p2 ../../../../../data/all/prop-direct-P86 ../../../../../data/all/prop-direct-P2886
./p2 ../../../../../data/all/prop-direct-P175 ../../../../../data/all/prop-direct-P2581
./p2 ../../../../../data/all/prop-direct-P30 ../../../../../data/all/prop-direct-P1465
./p2 ../../../../../data/all/prop-direct-P647 ../../../../../data/all/prop-direct-P910
./p2 ../../../../../data/all/prop-direct-P196 ../../../../../data/all/prop-direct-P1014
./p2 ../../../../../data/all/prop-direct-P176 ../../../../../data/all/prop-direct-P2174
./p2 ../../../../../data/all/prop-direct-P4952 ../../../../../data/all/prop-direct-P123
./p2 ../../../../../data/all/prop-direct-P376 ../../../../../data/all/prop-direct-P948
./p2 ../../../../../data/all/prop-direct-P282 ../../../../../data/all/prop-direct-normalized-P2581
./p2 ../../../../../data/all/prop-direct-P674 ../../../../../data/all/prop-direct-P241
./p2 ../../../../../data/all/prop-direct-P5277 ../../../../../data/all/prop-direct-P910
./p2 ../../../../../data/all/prop-direct-P509 ../../../../../data/all/prop-direct-P1375
./p2 ../../../../../data/all/prop-direct-P3578 ../../../../../data/all/prop-direct-P5166
